### ISSUE TITLE
VGGNet Pytorch Implementation Training Network에서 acc 변수에 대해 질문드립니다.

### ISSUE THREAD

**Issue by underthelights** [jjerry-k/learning_framework#2]
안녕하세요.
PyTorch를 공부하는 학생입니다. 
VGGNet의 Pytorch 를 실행시켜보던 중, 네트워크를 Training하던 중 acc 에 관한 변수가 선언되어있지 않아서 질문 드립니다.

**Comment by jjerry-k** [comment]
답변이 너무... 늦었네요.. 죄송합니다..ㅎ

지워도 되는 부분입니다!  

원래는 training accuracy를 출력하려 했으나 필요없다고 판단하여.. 지우는 과정에서 누락되었나보네요.

조만간 전반적인 코드 수정을 할 듯합니다.

감사합니다!
